version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1